curl -X POST "http://127.0.0.1:8000/timeline" \
     -H "Content-Type: application/json" \
     -d '{
      "coordinateSystem": "geo",
      "startDate": "2024-01-01",
      "endDate": "2025-01-01",
      "intervalMinutes": 60,
      "points": ["mercury"],
      "aspects": 
      [
          {
              "angle": 15,
              "family": true,
              "orb": 0.1,
              "targets": ["sun"]
          }
      ]
    }'

###

curl -X POST "http://localhost:8002/timeline" \
     -H "Content-Type: application/json" \
     -d '{
      "coordinateSystem": "geo",
      "startDate": "2024-01-01",
      "endDate": "2025-01-01",
      "intervalMinutes": 60,
      "points": ["mercury"],
      "aspects": 
      [
          {
              "angle": 15,
              "family": true,
              "orb": 0.1,
              "targets": ["sun"]
          }
      ]
    }'